import { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';

const siemensSolutions = [
  {
    id: 1,
    title: 'TIA Portal',
    description: 'Totally Integrated Automation Portal - integrated engineering framework for configuring, programming, and commissioning automation systems.',
    icon: '🔄',
    features: [
      'Unified engineering environment',
      'Integrated controller and HMI programming',
      'Centralized data management',
      'Simulation capabilities',
      'Diagnostics and maintenance tools'
    ]
  },
  {
    id: 2,
    title: 'SIMATIC WinCC',
    description: 'Scalable SCADA system for plant-wide visualization and control, from machine-level HMI to enterprise-wide monitoring.',
    icon: '📊',
    features: [
      'Plant-wide visualization',
      'Extensive reporting and analytics',
      'Open architecture with APIs',
      'Integrated alarming system',
      'Historical data archiving'
    ]
  },
  {
    id: 3,
    title: 'SIMATIC PCS 7',
    description: 'Distributed control system (DCS) for comprehensive plant automation, specializing in continuous process industries.',
    icon: '🏭',
    features: [
      'Integrated engineering and operations',
      'Flexible system architecture',
      'Advanced process control',
      'Batch processing capabilities',
      'Comprehensive asset management'
    ]
  },
  {
    id: 4,
    title: 'Plant Simulation',
    description: 'Discrete event simulation software for optimizing material flow, resource utilization, and logistics across all system levels.',
    icon: '📈',
    features: [
      '3D modeling and simulation',
      'Production analysis and optimization',
      'Bottleneck identification',
      'Energy efficiency analysis',
      'Virtual commissioning'
    ]
  },
  {
    id: 5,
    title: 'MindSphere',
    description: 'Industrial IoT as a service solution that connects your products, plants, systems, and machines to harness the wealth of data generated by IoT.',
    icon: '☁️',
    features: [
      'Cloud-based IoT operating system',
      'Secure data collection and connectivity',
      'Industrial analytics applications',
      'Developer environment and APIs',
      'Digital twin enablement'
    ]
  },
  {
    id: 6,
    title: 'SIMIT Simulation',
    description: 'Virtual commissioning platform for comprehensive simulation of automation systems before real-world implementation.',
    icon: '🎮',
    features: [
      'Virtual controller testing',
      'Operator training scenarios',
      'Process and plant simulation',
      'Integration with real control systems',
      'Reduced commissioning time'
    ]
  }
];

const siemensServices = [
  {
    title: 'Licensing & Procurement',
    description: 'Streamlined procurement of Siemens software licenses with competitive pricing and expert guidance.',
    icon: '🏷️'
  },
  {
    title: 'Implementation & Configuration',
    description: 'Professional installation, setup, and configuration of Siemens software solutions tailored to your requirements.',
    icon: '⚙️'
  },
  {
    title: 'Application Development',
    description: 'Custom development of specialized applications, templates, and add-ons to extend Siemens software capabilities.',
    icon: '💻'
  },
  {
    title: 'Training & Certification',
    description: 'Comprehensive training programs from basic to advanced levels, including official Siemens certification paths.',
    icon: '👨‍🏫'
  },
  {
    title: 'System Integration',
    description: 'Seamless integration of Siemens software with existing systems, including ERP, MES, PLM, and legacy applications.',
    icon: '🔌'
  },
  {
    title: 'Support & Maintenance',
    description: 'Ongoing technical support, troubleshooting, and regular maintenance services for your Siemens software environment.',
    icon: '🛠️'
  }
];

const SiemensSoftware = () => {
  useEffect(() => {
    document.title = 'Siemens Software Solutions - AUTOMAX';
    // Scroll to top when component mounts
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="pt-16">
      {/* Hero Section */}
      <section className="bg-primary py-20 md:py-28">
        <div className="container-custom">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="max-w-3xl"
          >
            <h1 className="text-4xl md:text-5xl font-bold mb-6 text-white">Siemens Software Solutions</h1>
            <p className="text-xl text-blue-100">
              As a Siemens Solution Partner, we provide comprehensive automation and digitalization software
              solutions that enable industrial transformation and enhanced manufacturing efficiency.
            </p>
          </motion.div>
        </div>
      </section>

      {/* Overview Section */}
      <section className="py-16 bg-white">
        <div className="container-custom">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="grid grid-cols-1 lg:grid-cols-2 gap-10 items-center"
          >
            <div>
              <h2 className="text-3xl font-bold mb-6 text-gray-800">Siemens: Pioneering Digital Transformation</h2>
              <p className="text-gray-600 mb-6">
                Siemens offers an extensive portfolio of industrial software solutions that span the entire value 
                chain - from product design and production planning to engineering, execution, and services. 
                These integrated solutions help organizations digitalize their entire industrial process chain.
              </p>
              <p className="text-gray-600 mb-6">
                As a certified Siemens Solution Partner, we deliver the full spectrum of Siemens industrial 
                software along with expert implementation services, customization, training, and support to 
                help you maximize your digital transformation journey.
              </p>
              <div className="grid grid-cols-2 gap-4 mt-8">
                <div className="bg-gray-50 p-4 rounded-lg">
                  <div className="text-primary font-bold text-xl mb-1">45%</div>
                  <p className="text-sm text-gray-600">Average productivity gain</p>
                </div>
                <div className="bg-gray-50 p-4 rounded-lg">
                  <div className="text-primary font-bold text-xl mb-1">300+</div>
                  <p className="text-sm text-gray-600">Siemens projects delivered</p>
                </div>
                <div className="bg-gray-50 p-4 rounded-lg">
                  <div className="text-primary font-bold text-xl mb-1">20+</div>
                  <p className="text-sm text-gray-600">Certified Siemens specialists</p>
                </div>
                <div className="bg-gray-50 p-4 rounded-lg">
                  <div className="text-primary font-bold text-xl mb-1">12+</div>
                  <p className="text-sm text-gray-600">Years as Solution Partner</p>
                </div>
              </div>
            </div>
            <div>
              <img 
                src="https://images.pexels.com/photos/3862136/pexels-photo-3862136.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" 
                alt="Siemens Software" 
                className="rounded-lg shadow-lg w-full h-auto"
              />
            </div>
          </motion.div>
        </div>
      </section>

      {/* Solutions Section */}
      <section className="py-16 bg-gray-50">
        <div className="container-custom">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="text-center max-w-3xl mx-auto mb-16"
          >
            <h2 className="text-3xl font-bold mb-4 text-gray-800">Siemens Software Portfolio</h2>
            <p className="text-gray-600">
              Explore the comprehensive range of Siemens software solutions that we offer to address 
              various industrial automation and digitalization challenges.
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {siemensSolutions.map((solution, index) => (
              <motion.div
                key={solution.id}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                viewport={{ once: true }}
                className="bg-white rounded-lg shadow-md overflow-hidden hover:shadow-lg transition-all duration-300"
              >
                <div className="p-6">
                  <div className="text-3xl mb-4">{solution.icon}</div>
                  <h3 className="text-2xl font-bold mb-3 text-gray-800">{solution.title}</h3>
                  <p className="text-gray-600 mb-4">{solution.description}</p>
                  
                  <h4 className="font-semibold text-gray-700 mb-2">Key Features:</h4>
                  <ul className="space-y-2">
                    {solution.features.map((feature, i) => (
                      <li key={i} className="flex items-start">
                        <svg className="w-5 h-5 text-primary mt-1 mr-2 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
                          <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd"></path>
                        </svg>
                        <span>{feature}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Benefits Section */}
      <section className="py-16 bg-white">
        <div className="container-custom">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="text-center max-w-3xl mx-auto mb-16"
          >
            <h2 className="text-3xl font-bold mb-4 text-gray-800">Digital Transformation Benefits</h2>
            <p className="text-gray-600">
              Implementing Siemens software solutions delivers significant advantages across your 
              entire industrial value chain.
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {[
              {
                title: 'Accelerated Innovation',
                description: 'Reduce time-to-market by up to 50% through integrated product development and virtual validation.',
                icon: '🚀'
              },
              {
                title: 'Enhanced Productivity',
                description: 'Optimize production planning and execution for increased throughput and resource utilization.',
                icon: '📈'
              },
              {
                title: 'Improved Quality',
                description: 'Ensure consistent product quality through comprehensive monitoring, analytics, and closed-loop quality processes.',
                icon: '✓'
              },
              {
                title: 'Operational Flexibility',
                description: 'Adapt quickly to changing market requirements with agile manufacturing systems and processes.',
                icon: '🔄'
              },
              {
                title: 'Reduced Costs',
                description: 'Lower production costs through optimized resource utilization, energy efficiency, and minimized downtime.',
                icon: '💰'
              },
              {
                title: 'Data-Driven Decisions',
                description: 'Make informed decisions based on real-time operational data and advanced analytics insights.',
                icon: '📊'
              }
            ].map((benefit, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                viewport={{ once: true }}
                className="bg-gray-50 rounded-lg p-6 shadow-sm hover:shadow-md transition-all duration-300"
              >
                <div className="text-3xl mb-4">{benefit.icon}</div>
                <h3 className="text-xl font-bold mb-2 text-gray-800">{benefit.title}</h3>
                <p className="text-gray-600">{benefit.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Services Section */}
      <section className="py-16 bg-gray-50">
        <div className="container-custom">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="text-center max-w-3xl mx-auto mb-16"
          >
            <h2 className="text-3xl font-bold mb-4 text-gray-800">Our Siemens Software Services</h2>
            <p className="text-gray-600">
              We offer a comprehensive range of services to ensure successful implementation and 
              optimal utilization of your Siemens software investments.
            </p>
          </motion.div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
            {siemensServices.map((service, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                viewport={{ once: true }}
                className="bg-white rounded-lg p-6 shadow-md hover:shadow-lg transition-all duration-300"
              >
                <div className="text-3xl mb-4">{service.icon}</div>
                <h3 className="text-xl font-bold mb-2 text-gray-800">{service.title}</h3>
                <p className="text-gray-600">{service.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Implementation Approach */}
      <section className="py-16 bg-white">
        <div className="container-custom">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="text-center max-w-3xl mx-auto mb-16"
          >
            <h2 className="text-3xl font-bold mb-4 text-gray-800">Our Implementation Methodology</h2>
            <p className="text-gray-600">
              We follow a proven, systematic approach to implementing Siemens software solutions 
              that ensures success and maximizes your return on investment.
            </p>
          </motion.div>

          <div className="relative">
            {/* Connecting line */}
            <div className="absolute left-1/2 transform -translate-x-1/2 top-0 bottom-0 w-1 bg-primary-light hidden md:block"></div>
            
            <div className="space-y-12">
              {[
                {
                  title: 'Discovery & Assessment',
                  description: 'We thoroughly analyze your current processes, systems, and requirements to create a strategic implementation roadmap.',
                  icon: '🔍'
                },
                {
                  title: 'Solution Design',
                  description: 'Our experts design a tailored solution architecture that aligns with your business objectives and technical requirements.',
                  icon: '📝'
                },
                {
                  title: 'Implementation & Integration',
                  description: 'We handle software installation, configuration, customization, and integration with your existing systems.',
                  icon: '⚙️'
                },
                {
                  title: 'Testing & Validation',
                  description: 'Comprehensive testing ensures all functionality works as expected and meets your specific requirements.',
                  icon: '✓'
                },
                {
                  title: 'Training & Knowledge Transfer',
                  description: 'We provide tailored training programs to ensure your team can effectively utilize and maintain the system.',
                  icon: '👨‍🏫'
                },
                {
                  title: 'Ongoing Support & Optimization',
                  description: 'Our support continues beyond implementation with maintenance, updates, and continuous improvement services.',
                  icon: '🔄'
                }
              ].map((step, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5, delay: index * 0.1 }}
                  viewport={{ once: true }}
                  className={`flex items-start md:items-center ${index % 2 === 0 ? 'md:flex-row' : 'md:flex-row-reverse'}`}
                >
                  <div className={`hidden md:flex flex-1 ${index % 2 === 0 ? 'justify-end pr-8' : 'justify-start pl-8'}`}>
                    <div className="bg-white rounded-lg shadow-md p-6 max-w-md">
                      <h3 className="text-xl font-bold mb-2 text-gray-800">{step.title}</h3>
                      <p className="text-gray-600">{step.description}</p>
                    </div>
                  </div>
                  
                  <div className="relative flex-shrink-0 mx-2 md:mx-0 z-10">
                    <div className="w-12 h-12 bg-primary rounded-full flex items-center justify-center text-white text-xl font-bold shadow-md">
                      {step.icon}
                    </div>
                  </div>
                  
                  <div className="md:hidden flex-1 pl-4">
                    <div className="bg-white rounded-lg shadow-md p-6">
                      <h3 className="text-xl font-bold mb-2 text-gray-800">{step.title}</h3>
                      <p className="text-gray-600">{step.description}</p>
                    </div>
                  </div>
                  
                  <div className={`hidden md:flex flex-1 ${index % 2 === 0 ? 'justify-start pl-8' : 'justify-end pr-8'}`}></div>
                </motion.div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Success Story Section */}
      <section className="py-16 bg-gray-50">
        <div className="container-custom">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="text-center max-w-3xl mx-auto mb-16"
          >
            <h2 className="text-3xl font-bold mb-4 text-gray-800">Success Story</h2>
            <p className="text-gray-600">
              See how our Siemens software solutions have transformed operations for our clients.
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="bg-white rounded-lg shadow-md overflow-hidden"
          >
            <div className="grid grid-cols-1 lg:grid-cols-5 gap-0">
              <div className="lg:col-span-2 h-full">
                <img 
                  src="https://images.pexels.com/photos/1108101/pexels-photo-1108101.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" 
                  alt="Manufacturing Facility" 
                  className="w-full h-full object-cover"
                />
              </div>
              <div className="lg:col-span-3 p-8">
                <h3 className="text-2xl font-bold mb-3 text-gray-800">Automotive Components Manufacturer</h3>
                <p className="text-gray-600 mb-6">
                  A leading automotive components manufacturer needed to optimize their production processes,
                  improve quality control, and enhance operational visibility. By implementing Siemens TIA Portal 
                  and SIMATIC WinCC, we helped them achieve:
                </p>
                <ul className="space-y-3 mb-6">
                  <li className="flex items-start">
                    <svg className="w-5 h-5 text-primary mt-1 mr-2 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd"></path>
                    </svg>
                    <span className="text-gray-600">35% increase in overall equipment effectiveness (OEE)</span>
                  </li>
                  <li className="flex items-start">
                    <svg className="w-5 h-5 text-primary mt-1 mr-2 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd"></path>
                    </svg>
                    <span className="text-gray-600">70% reduction in quality defects through real-time monitoring</span>
                  </li>
                  <li className="flex items-start">
                    <svg className="w-5 h-5 text-primary mt-1 mr-2 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd"></path>
                    </svg>
                    <span className="text-gray-600">25% reduction in unplanned downtime through predictive maintenance</span>
                  </li>
                  <li className="flex items-start">
                    <svg className="w-5 h-5 text-primary mt-1 mr-2 flex-shrink-0" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd"></path>
                    </svg>
                    <span className="text-gray-600">Comprehensive plant-wide visibility through unified SCADA system</span>
                  </li>
                </ul>
                <div className="italic text-gray-600 border-l-4 border-primary pl-4 py-2">
                  "The Siemens software implementation has transformed our manufacturing operations. We now have unprecedented visibility into our processes and can make data-driven decisions in real-time."
                </div>
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 bg-white">
        <div className="container-custom">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="bg-gradient-to-r from-blue-900 to-primary rounded-xl p-8 md:p-12 text-white shadow-xl overflow-hidden relative"
          >
            <div className="absolute -right-20 -bottom-20 w-64 h-64 bg-white/10 rounded-full"></div>
            
            <div className="relative z-10 text-center max-w-3xl mx-auto">
              <h2 className="text-3xl md:text-4xl font-bold mb-6 text-white">
                Ready to Accelerate Your Digital Transformation?
              </h2>
              <p className="text-blue-100 mb-8 text-lg">
                Contact our Siemens software specialists to discuss how we can help you implement 
                cutting-edge industrial software solutions to optimize your operations.
              </p>
              <div className="flex flex-col sm:flex-row justify-center gap-4">
                <Link 
                  to="/contact" 
                  className="btn bg-white text-primary hover:bg-gray-100 transition-colors shadow-md"
                >
                  Schedule a Consultation
                </Link>
                <Link 
                  to="/contact" 
                  className="btn bg-transparent border-2 border-white text-white hover:bg-white/10 transition-colors"
                >
                  Request a Demo
                </Link>
              </div>
            </div>
          </motion.div>
        </div>
      </section>
    </div>
  );
};

export default SiemensSoftware; 